<?php
// module/Album/view/album/album/index.phtml:

$title = 'List tags';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('tag', ['action' => 'add']) ?>">ADD NEW</a>
</p>

<table class="table">
<tr>
    <th>Name</th>
    <th>Description</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($tags as $tag) : ?>
    <tr>
        <td><?= $this->escapeHtml($tag->tag_name) ?></td>
        <td><?= $this->escapeHtml($tag->tag_description) ?></td>
        <td>
            <a href="<?= $this->url('tag', ['action' => 'edit', 'id' => $tag->id]) ?>">Edit</a>
            <a href="<?= $this->url('tag', ['action' => 'delete', 'id' => $tag->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>