<?php
    $this->headTitle($mt);
?>

<h1 class="page-header"><?= $mt ?></h1>

<?php if(count($categories) > 0) : ?>
    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($categories as $category) : ?>
            <tr>
                <td>
                    <?= $this->escapeHtml($category->category_name) ?>
                </td>
                <td>
                    <?= $this->escapeHtml($category->category_description) ?>
                </td>
                <td class="center">
                    <a href="<?= $this->url('category', ['action' => 'edit', 'id' => $category->id]) ?>" class="btn btn-primary btn-xs">Edit</a> 
                    <a href="<?= $this->url('category', ['action' => 'delete', 'id' => $category->id]) ?>" class="btn btn-danger btn-xs">Delete</a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else : ?>
    <center>
        <font color="red">
            No categories existed or config file not found!
        </font>
    </center>
<?php endif; ?>    

<a href="<?= $this->url('category', ['action' => 'add']) ?>" class="btn btn-primary">ADD NEW</a>