<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <?= $this->headTitle('Zend Framework Admin')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headLink()
            ->prependStylesheet($this->basePath('admin/vendor/font-awesome/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('admin/dist/css/sb-admin-2.css'))
            ->prependStylesheet($this->basePath('admin/vendor/metisMenu/metisMenu.min.css'))
            ->prependStylesheet($this->basePath('admin/vendor/bootstrap/css/bootstrap.min.css'))
    ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Zend Framework 3 Admin</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="#"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        
                        <li>
                            <a href="<?= $this->url('post', ['action' => 'index']) ?>"><i class="fa fa-edit fa-fw"></i> Posts<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?= $this->url('post', ['action' => 'index']) ?>">All Posts</a>
                                </li>
                                <li>
                                    <a href="<?= $this->url('post', ['action' => 'add']) ?>">Add New</a>
                                </li>
                                <li>
                                    <a href="<?= $this->url('category', ['action' => 'index']) ?>">Categories</a>
                                </li>
                                <li>
                                    <a href="<?= $this->url('tag', ['action' => 'index']) ?>">Tags</a>
                                </li>
                            </ul>
                        </li>
                        
                        <li>
                            <a href="<?= $this->url('page', ['action' => 'index']) ?>"><i class="fa fa-files-o fa-fw"></i> Pages<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?= $this->url('page', ['action' => 'index']) ?>">All Pages</a>
                                </li>
                                <li>
                                    <a href="<?= $this->url('page', ['action' => 'add']) ?>">Add New</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <?= $this->content ?>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <?= $this->headScript()
            ->prependFile($this->basePath('js/summernote/summernote.js'))
            ->prependFile($this->basePath('js/ckeditor/ckeditor.js'))
            ->prependFile($this->basePath('admin/dist/js/sb-admin-2.js'))
            ->prependFile($this->basePath('admin/vendor/metisMenu/metisMenu.min.js'))
            ->prependFile($this->basePath('admin/vendor/bootstrap/js/bootstrap.min.js'))
            ->prependFile($this->basePath('admin/vendor/jquery/jquery.min.js'))
    ?>

    <?= $this->headLink()
            ->prependStylesheet($this->basePath('js/summernote/summernote.css'))
    ?>

    <!-- Select2 -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script type="text/javascript">
        $('select.select2').select2();
    </script>

    <!-- CKEditor -->
    <script type="text/javascript">
        $(document).ready(function() {
            CKEDITOR.replace( 'ckeditor' );
        });
    </script>

    <!-- Summernote -->
    <script type="text/javascript">
        $(document).ready(function() {
            $('.summernote').summernote({
                height: 300
            });
        });
    </script>
</body>

</html>