<?php
    $this->headTitle($mt);
?>

<h1 class="page-header"><?= $mt ?></h1>

<p>
    <a href="<?= $this->url($singular, ['action' => 'add']) ?>" class="btn btn-primary">
        <i class="fa fa-plus"></i> ADD NEW
    </a>
</p>

<?php if(count($cruds) > 0 && !empty($config)) : ?>
    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
        <thead>
            <tr>
                <th><input type="checkbox" /></th>
                <?php foreach($config->display->index as $cdi) : ?>
                <th><?= $config->cols->$cdi->label ?></th>
                <?php endforeach; ?>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($cruds as $crud) : ?>
            <tr>
                <td><input type="checkbox" /></td>
                <?php foreach($config->display->index as $cdi) : ?>
                <td>
                    <?= strip_tags($crud->$cdi) ?>
                </td>
                <?php endforeach; ?>
                <td class="center">
                    <a href="<?= $this->url($singular, ['action' => 'edit', 'id' => $crud->id]) ?>" class="btn btn-default btn-xs">
                        <i class="fa fa-edit"></i> Edit
                    </a>

                    <a href="<?= $this->url($singular, ['action' => 'delete', 'id' => $crud->id]) ?>" class="btn btn-default btn-xs">
                        <i class="fa fa-trash"></i> Delete
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else : ?>
    <center>
        <font color="red">
            No <?= $plural ?> existed or config file not found!
        </font>
    </center>
<?php endif; ?>    

