<?php
// module/Album/view/album/album/index.phtml:

$title = 'List pages';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('page', ['action' => 'add']) ?>">ADD NEW</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Image</th>
    <th>Content</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($pages as $page) : ?>
    <tr>
        <td><?= $this->escapeHtml($page->page_title) ?></td>
        <td></td>
        <td><?= $this->escapeHtml($page->page_content) ?></td>
        <td>
            <a href="<?= $this->url('page', ['action' => 'edit', 'id' => $page->id]) ?>">Edit</a>
            <a href="<?= $this->url('page', ['action' => 'delete', 'id' => $page->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>