<?php
    $this->headTitle($mt);
?>

<h1 class="page-header"><?= $mt ?></h1>

<?php if(count($pages) > 0) : ?>
    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
        <thead>
            <tr>
                <th>Title</th>
                <th>Image</th>
                <th>Content</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($pages as $page) : ?>
            <tr>
                <td>
                    <?= $this->escapeHtml($page->page_title) ?>
                </td>
                <td></td>
                <td>
                    <?= $this->escapeHtml($page->page_content) ?>
                </td>
                <td class="center">
                    <a href="<?= $this->url('page', ['action' => 'edit', 'id' => $page->id]) ?>" class="btn btn-primary btn-xs">Edit</a> 
                    <a href="<?= $this->url('page', ['action' => 'delete', 'id' => $page->id]) ?>" class="btn btn-danger btn-xs">Delete</a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else : ?>
    <center>
        <font color="red">
            No pages existed or config file not found!
        </font>
    </center>
<?php endif; ?>    

<a href="<?= $this->url('page', ['action' => 'add']) ?>" class="btn btn-primary">ADD NEW</a>